### ISSUE TITLE
Any progress?

### ISSUE THREAD

**Issue by asmikhailov** [savoirfairelinux/sflvault#11]
Will be any new release? 
Client-Qt now is not working. Problems with Keyring attribute supported, parsing input datas, etc.
may be a web-interface?

**Comment by cormier** [comment]
Hi @asmikhailov and thanks for the question. Yes, there is some developement scheduled for the future. We are currently scheduling release of 0.8 containing at least the keyring fix.

A web interface would definitely be nice, but difficult considering the fact that encryption is done client side.

What exactly is the issue with the QT Client, and what do you mean by "parsing input datas"? Should we fill a specific issue for those? Are those issues something for which you have a fix?

**Comment by asmikhailov** [comment]
i did some attepmts to compile and install Qt Client
excluding, by the way, from client/client.py test for keyring checks (it doesn't work at all for me)
Client successful installed and run but every time i try add something like a machine, service etc i got error message like this:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/SFLvault_client_qt-0.7.8.2-py2.7.egg/sflvault/clientqt/gui/mainWindow.py", line 690, in addService
    self.addservice.exec_()
  File "/usr/local/lib/python2.7/dist-packages/SFLvault_client_qt-0.7.8.2-py2.7.egg/sflvault/clientqt/gui/config/service.py", line 485, in exec_
    self.fillServicesList()
  File "/usr/local/lib/python2.7/dist-packages/SFLvault_client_qt-0.7.8.2-py2.7.egg/sflvault/clientqt/gui/config/service.py", line 382, in fillServicesList
    services = listService()
  File "/usr/local/lib/python2.7/dist-packages/SFLvault_client_qt-0.7.8.2-py2.7.egg/sflvault/clientqt/lib/auth.py", line 146, in try_func
    status = func(*k, **a)
  File "/usr/local/lib/python2.7/dist-packages/SFLvault_client_qt-0.7.8.2-py2.7.egg/sflvault/clientqt/lib/auth.py", line 158, in reauth_func
    if 'error' in status and status["error"]:
TypeError: argument of type 'NoneType' is not iterable

**Comment by cormier** [comment]
Thanks! I have filed a specific issue for this. What about the "parsing input datas" issue? Should we file a specific issue for this one as well?

**Comment by asmikhailov** [comment]
seems like my english make a double trouble. "parsing input datas" was exactly error with entering attributes for machina record.
i should note - command line based client works without any errors.

**Comment by cormier** [comment]
OK, so the issue with "parsing input datas" is the issue reported as #12? Can I close the current issue?

**Comment by asmikhailov** [comment]
yes. you can
