### ISSUE TITLE
Problem compiling the QT client

### ISSUE THREAD

**Issue by cormier** [savoirfairelinux/sflvault#12]
@asmikhailov has written in #11 :

> i did some attepmts to compile and install Qt Client
> excluding, by the way, from client/client.py test for keyring checks (it doesn't work at all for me)
> Client successful installed and run but every time i try add something like a machine, service etc i got error message like this:

```shell
Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/SFLvault_client_qt-0.7.8.2-py2.7.egg/sflvault/clientqt/gui/mainWindow.py", line 690, in addService
self.addservice.exec_()
File "/usr/local/lib/python2.7/dist-packages/SFLvault_client_qt-0.7.8.2-py2.7.egg/sflvault/clientqt/gui/config/service.py", line 485, in exec_
self.fillServicesList()
File "/usr/local/lib/python2.7/dist-packages/SFLvault_client_qt-0.7.8.2-py2.7.egg/sflvault/clientqt/gui/config/service.py", line 382, in fillServicesList
services = listService()
File "/usr/local/lib/python2.7/dist-packages/SFLvault_client_qt-0.7.8.2-py2.7.egg/sflvault/clientqt/lib/auth.py", line 146, in try_func
status = func(k, *a)
File "/usr/local/lib/python2.7/dist-packages/SFLvault_client_qt-0.7.8.2-py2.7.egg/sflvault/clientqt/lib/auth.py", line 158, in reauth_func
if 'error' in status and status["error"]:
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by Apteryks** [comment]
With the recent port of the client code to Python 3, it appears the Qt client is no longer working.  Will  track these issues together here.
