### ISSUE TITLE
Crash when editing a service with a special character in description

### ISSUE THREAD

**Issue by philippemouchel** [savoirfairelinux/sflvault#26]
Hi there !

I created a service and fill its description using a special character : è
Now, I want to edit it, but it's impossible as my client crash : 

Here is the error code : 
```
SFLvault> service-edit 6430
Authentication successful
Traceback (most recent call last):
  File "/usr/local/bin/sflvault", line 9, in <module>
    load_entry_point('SFLvault-client==0.7.8.2', 'console_scripts', 'sflvault')()
  File "/usr/local/lib/python2.7/dist-packages/sflvault/client/commands.py", line 1061, in main
    s._run()
  File "/usr/local/lib/python2.7/dist-packages/sflvault/client/commands.py", line 101, in _run
    runcmd._run(args)
  File "/usr/local/lib/python2.7/dist-packages/sflvault/client/commands.py", line 184, in _run
    getattr(self, action)()
  File "/usr/local/lib/python2.7/dist-packages/sflvault/client/commands.py", line 523, in service_edit
    decrypt=False)
  File "/usr/local/lib/python2.7/dist-packages/sflvault/client/commands.py", line 568, in _something_edit
    dialog = ui_class(thing)
  File "/usr/local/lib/python2.7/dist-packages/sflvault/client/ui.py", line 172, in __init__
    'notes': urwid.Edit("", str(data['notes'])),
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe8' in position 83: ordinal not in range(128)
```

**Comment by support-savoirfairelinux** [comment]
This issue is resolved by the Python 3 port, which was just merged into master. Closing. Thanks for the report!
