### ISSUE TITLE
Non-ascii characters triggers UnicodeEncodeError crash

### ISSUE THREAD

**Issue by Apteryks** [savoirfairelinux/sflvault#40]
Use of French accentuated characters (in machine description for example) lead to:
```
SFLvault> machine-edit 2533
Authentication successful
Traceback (most recent call last):
  File "/opt/SFLvault-client-0.7.8/bin/sflvault", line 11, in <module>
    sys.exit(main())
  File "/opt/SFLvault-client-0.7.8/local/lib/python2.7/site-packages/sflvault/client/commands.py", line 1061, in main
    s._run()
  File "/opt/SFLvault-client-0.7.8/local/lib/python2.7/site-packages/sflvault/client/commands.py", line 101, in _run
    runcmd._run(args)
  File "/opt/SFLvault-client-0.7.8/local/lib/python2.7/site-packages/sflvault/client/commands.py", line 184, in _run
    getattr(self, action)()
  File "/opt/SFLvault-client-0.7.8/local/lib/python2.7/site-packages/sflvault/client/commands.py", line 531, in machine_edit
    'machine-edit aborted')
  File "/opt/SFLvault-client-0.7.8/local/lib/python2.7/site-packages/sflvault/client/commands.py", line 568, in _something_edit
    dialog = ui_class(thing)
  File "/opt/SFLvault-client-0.7.8/local/lib/python2.7/site-packages/sflvault/client/ui.py", line 247, in __init__
    inputs[x] = urwid.Edit("", str(data[x])) # , wrap='clip'
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 1: ordinal not in range(128)

**Comment by ventilooo** [comment]
@Apteryks 

Thanks for you issue :smile: 
To fix this you should set your locale to utf-8

**exemple for en_US locale :**
```
export LC_ALL="en_US.UTF-8"
export LC_CTYPE="en_US.UTF-8"
sudo dpkg-reconfigure locales
```

**Comment by Apteryks** [comment]
Hmm, I'm already using a utf-8 locale:

```
locale
LANG=fr_CA.UTF-8
LANGUAGE=fr_CA:fr
LC_CTYPE="fr_CA.UTF-8"
LC_NUMERIC="fr_CA.UTF-8"
LC_TIME="fr_CA.UTF-8"
LC_COLLATE="fr_CA.UTF-8"
LC_MONETARY="fr_CA.UTF-8"
LC_MESSAGES="fr_CA.UTF-8"
LC_PAPER="fr_CA.UTF-8"
LC_NAME="fr_CA.UTF-8"
LC_ADDRESS="fr_CA.UTF-8"
LC_TELEPHONE="fr_CA.UTF-8"
LC_MEASUREMENT="fr_CA.UTF-8"
LC_IDENTIFICATION="fr_CA.UTF-8"
LC_ALL=
```
I've tried: "LC_ALL=en_US.UTF-8 sflvault machine-edit 2533" but it fails in the same way.

**Comment by support-savoirfairelinux** [comment]
This issue is now resolved, thanks to Python 3 support. Closing.
