### ISSUE TITLE
sflvault requires keyring <= 1.6.1

### ISSUE THREAD

**Issue by Apteryks** [savoirfairelinux/sflvault#51]
Using keyring > 1.6.1 causes errors when using the wallet command, such as:

```
sflvault wallet
Traceback (most recent call last):
  File "/gnu/store/v264g9s2w9ycdsf4ylyk4d0c2q0hbjhy-sflvault-client-0.7.8.2/bin/.sflvault-real", line 11, in <module>
    load_entry_point('SFLvault-client==0.7.8.2', 'console_scripts', 'sflvault')()
  File "/gnu/store/v264g9s2w9ycdsf4ylyk4d0c2q0hbjhy-sflvault-client-0.7.8.2/lib/python2.7/site-packages/sflvault/client/commands.py", line 1067, in main
    f._run(args[1:])
  File "/gnu/store/v264g9s2w9ycdsf4ylyk4d0c2q0hbjhy-sflvault-client-0.7.8.2/lib/python2.7/site-packages/sflvault/client/commands.py", line 184, in _run
    getattr(self, action)()
  File "/gnu/store/v264g9s2w9ycdsf4ylyk4d0c2q0hbjhy-sflvault-client-0.7.8.2/lib/python2.7/site-packages/sflvault/client/commands.py", line 956, in wallet
    for i, name, obj, status, current in self.vault.cfg.wallet_list():
  File "/gnu/store/v264g9s2w9ycdsf4ylyk4d0c2q0hbjhy-sflvault-client-0.7.8.2/lib/python2.7/site-packages/sflvault/client/client.py", line 310, in wallet_list
    ref[backend.supported()],
AttributeError: 'Keyring' object has no attribute 'supported'
```

This is the same problem as reported for Backintime: https://github.com/bit-team/backintime/issues/44.  They fixed it with this commit: https://github.com/bit-team/backintime/commit/78ffd4dd0872448a77cd6e2328b3c6a1b2369b86

keyring is currently at version 19.2.0 (see: https://pypi.org/project/keyring/)

**Comment by Apteryks** [comment]
Keyring 1.6.1 can be used until Python 3.8, after which it breaks on a deprecated call to base64.decodestring.
